management:
  endpoints:
    web:
      base-path: "/manage"

env-test:
  env: ${env_test}

spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: config
      profile: ${profile}
